spring:
  datasource:
    generate-unique-name: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  profiles:
    active:
      - dev

server:
  error:
    include-message: always
    include-binding-errors: always

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/hoaxify
    username: jmmm
    password: 1234
  jpa:
    hibernate:
      # and to update the tables if the entity's have new fields, setting this to
      ddl-auto: update
hoaxify:
  upload-path: uploads-prod
---
spring:
    profiles: dev
    datasource:
      url: jdbc:h2:mem:hoaxify-dev
hoaxify:
    upload-path: uploads-dev
---
spring:
  profiles: test
hoaxify:
  upload-path: uploads-test