spring:
  datasource:
    generate-unique-name: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        page-parameter: currentPage
        size-parameter: pageSize

server:
  error:
    include-message: always
    include-binding-errors: always